url: "https://masbastudio.my" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Masba Studio" # the name of your site, e.g. ACME Corp.
timezone: UTC
