- title: "T-Shirt Sublimation"
  description: "High-quality custom T-shirt printing for events, brands, and gifts."
  image: "assets/images/Potrait/T-SHIRT PRINTING.png"

- title: "Graphic Design"
  description: "Creative and impactful visuals, posters, and logos for your business."
  image: "assets/images/08-tag-mockup.png"

- title: "Video Editing"
  description: "Clean, engaging, and promotional videos that boost your online presence."
  image: "assets/images/Potrait/LANYARD + ID CARD PRINTING.png"

- title: "Simple Website"
  description: "Modern, mobile-friendly websites to showcase your products or services."
  image: "assets/images/Potrait/CUSTOM MUG PRINTING.jpg"
